output "key_id" {
  value       = azuread_application_password.main.key_id
  description = "A UUID used to uniquely identify this password credential."
}

output "value" {
  value       = azuread_application_password.main.value
  description = "The password for this application, which is generated by Azure Active Directory."
  sensitive   = true
}